title = "Myelin"
description = "Designing the Future of Artifical Intelligence"
url_prefix = "https://www.myelin.ch"

[[pages]]
path = "/"
file = "index"

[[pages]]
file = "404"
title = "Page Not Found"

[[pages]]
path = "/team"
file = "team"
title = "Team"

# [[pages]]
# path = "/vision"
# file = "vision"
# title = "Vision"

[additional]
website_repo = "myelin-ai/website"
blog_url = "https://blog.myelin.ch"

[[additional.people]]
name = "Jan Hohenheim"
username = "janhohenheim"
image_url = "https://avatars2.githubusercontent.com/u/9047632"

[[additional.people]]
name = "Ruben Schmidmeister"
username = "bash"
image_url = "https://avatars2.githubusercontent.com/u/4602612"

[[additional.people]]
name = "Mathias Fischler"
username = "Mafii"
image_url = "https://avatars2.githubusercontent.com/u/10061519"

[[additional.people]]
name = "Jeremy Stucki"
username = "jeremystucki"
image_url = "assets://jeremy"

[assets]
style = { source = "sass/style.scss" }
whitepaper_js = { source = "assets/whitepaper.js" }
header_logo = { source = "assets/header-logo.svg" }
github_icon = { source = "assets/github-icon.svg" }
jeremy = { source = "assets/jeremy.jpg" }
wave_line = { source = "assets/wave-line.svg" }
brain_icon = { source = "assets/icons/brain.svg" }
helix_icon = { source = "assets/icons/helix.svg" }
processor_icon = { source = "assets/icons/processor.svg" }
lightbulb_icon = { source = "assets/icons/lightbulb.svg" }
favicon_16 = { source = "assets/favicons/favicon-16.png" }
favicon_32 = { source = "assets/favicons/favicon-32.png" }
favicon_128 = { source = "assets/favicons/favicon-128.png" }
safari_mask_icon = { source = "assets/favicons/safari-mask-icon.svg" }
apple_touch_icon = { source = "assets/favicons/apple-touch-icon.png" }
